version: '3'
services:
  obniz_python:
    restart: always
    build: .
    container_name: 'obniz_python'
    working_dir: '/root/opt'
    tty: true
    volumes:
      - ../:/root/opt
    ports:
      - "8080:8080"
      - "8081:8081"
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/opt'
    tty: true
    volumes:
      - ../prototypetest:/root/opt
